import { ToastContainer } from "react-toastify"
import Navbar from "./Components/Navbar"
import './globals.css'
import SessionProvider from "@/app/Components/SessionProvider";
import { getServerSession } from "next-auth";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <Navbar />
          {children}
          <ToastContainer
            position="bottom-right"
            autoClose={3000}
            theme="dark" />
        </SessionProvider>
      </body>
    </html>
  )
}
