import { ToastContainer } from "react-toastify"
import Navbar from "./Components/Navbar"
import './globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {/* <Drawer/> */}
        {children}
        <ToastContainer
          position="bottom-right"
          autoClose={3000}
          theme="dark" />
      </body>
    </html>
  )
}
