import { ToastContainer } from "react-toastify"
import 'react-toastify/dist/ReactToastify.css';
import Navbar from "./Components/Navbar"
import './globals.css'
import SessionProvider from "@/app/Components/SessionProvider";
import { NextUIProvider } from "@nextui-org/react";
import { getServerSession } from "next-auth";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className="dark text-foreground bg-background h-dvh">
        <SessionProvider session={session}>
          <NextUIProvider>
              <Navbar />
              {children}
          </NextUIProvider>
        </SessionProvider>
              <ToastContainer
                position="bottom-right"
                autoClose={3000}
                theme="dark" />
      </body>
    </html>
  )
}
